src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Index(name: 'card_type_index', columns: ['card_type'],flags: ['btree'])]
#[ORM\Entity(repositoryClass: CardRepository::class)]
class Card
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 63)]
    private ?string $title = null;

    // treasure or room
    #[ORM\Column(length: 31)]
    private ?string $card_type = null;

    // monster, change class/race, weapon, armor, curse
    #[ORM\Column(length: 31)]
    private ?string $card_action = null;

    // description of the card
    #[ORM\Column(length: 255)]
    private ?string $description = null;

    // field with monster level
    #[ORM\Column(type: 'integer')]
    private ?int $level = null;

    //field with monster level reward
    #[ORM\Column(type: 'integer')]
    private ?int $level_reward = null;

    //field with monster treasure reward
    #[ORM\Column(type: 'integer')]
    private ?int $treasure_reward = null;

    //field with monster description when you lose fight with monster
    #[ORM\Column(length: 255)]
    private ?string $lose_description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCardType(): ?string
    {
        return $this->card_type;
    }

    public function setCardType(string $card_type): static
    {
        $this->card_type = $card_type;

        return $this;
    }

    public function getCardAction(): ?string
    {
        return $this->card_action;
    }

    public function setCardAction(string $card_action): static
    {
        $this->card_action = $card_action;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getLevelReward(): ?int
    {
        return $this->level_reward;
    }

    public function setLevelReward(int $level_reward): static
    {
        $this->level_reward = $level_reward;

        return $this;
    }

    public function getTreasureReward(): ?int
    {
        return $this->treasure_reward;
    }

    public function setTreasureReward(int $treasure_reward): static
    {
        $this->treasure_reward = $treasure_reward;

        return $this;
    }

    public function getLoseDescription(): ?string
    {
        return $this->lose_description;
    }

    public function setLoseDescription(string $lose_description): static
    {
        $this->lose_description = $lose_description;

        return $this;
    }
}

src/Form/CardType.php
<?php

namespace App\Form;

use App\Entity\Card;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('card_type')
            ->add('card_action')
            ->add('description')
            ->add('level')
            ->add('level_reward')
            ->add('treasure_reward')
            ->add('lose_description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Card::class,
        ]);
    }
}

src/Controller/CardController.php
<?php

namespace App\Controller;

use App\Entity\Card;
use App\Form\CardType;
use App\Repository\CardRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/card')]
final class CardController extends AbstractController
{
    #[Route(name: 'app_card_index', methods: ['GET'])]
    public function index(CardRepository $cardRepository): Response
    {
        return $this->render('card/index.html.twig', [
            'cards' => $cardRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_card_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $card = new Card();
        $form = $this->createForm(CardType::class, $card);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($card);
            $entityManager->flush();

            return $this->redirectToRoute('app_card_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('card/new.html.twig', [
            'card' => $card,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_card_show', methods: ['GET'])]
    public function show(Card $card): Response
    {
        return $this->render('card/show.html.twig', [
            'card' => $card,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_card_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Card $card, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CardType::class, $card);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_card_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('card/edit.html.twig', [
            'card' => $card,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_card_delete', methods: ['POST'])]
    public function delete(Request $request, Card $card, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$card->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($card);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_card_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/card/_delete_form.html.twig
<form method="post" action="{{ path('app_card_delete', {'id': card.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ card.id) }}">
    <button class="btn">Delete</button>
</form>

templates/card/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Card{% endblock %}

{% block body %}
    <h1>Edit Card</h1>

    {{ include('card/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_card_index') }}">back to list</a>

    {{ include('card/_delete_form.html.twig') }}
{% endblock %}

templates/card/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Card index{% endblock %}

{% block body %}
    <h1>Card index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Card_type</th>
                <th>Card_action</th>
                <th>Description</th>
                <th>Level</th>
                <th>Level_reward</th>
                <th>Treasure_reward</th>
                <th>Lose_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for card in cards %}
            <tr>
                <td>{{ card.id }}</td>
                <td>{{ card.title }}</td>
                <td>{{ card.cardType }}</td>
                <td>{{ card.cardAction }}</td>
                <td>{{ card.description }}</td>
                <td>{{ card.level }}</td>
                <td>{{ card.levelReward }}</td>
                <td>{{ card.treasureReward }}</td>
                <td>{{ card.loseDescription }}</td>
                <td>
                    <a href="{{ path('app_card_show', {'id': card.id}) }}">show</a>
                    <a href="{{ path('app_card_edit', {'id': card.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_card_new') }}">Create new</a>
{% endblock %}

templates/card/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Card{% endblock %}

{% block body %}
    <h1>Create new Card</h1>

    {{ include('card/_form.html.twig') }}

    <a href="{{ path('app_card_index') }}">back to list</a>
{% endblock %}

templates/card/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Card{% endblock %}

{% block body %}
    <h1>Card</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ card.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ card.title }}</td>
            </tr>
            <tr>
                <th>Card_type</th>
                <td>{{ card.cardType }}</td>
            </tr>
            <tr>
                <th>Card_action</th>
                <td>{{ card.cardAction }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ card.description }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ card.level }}</td>
            </tr>
            <tr>
                <th>Level_reward</th>
                <td>{{ card.levelReward }}</td>
            </tr>
            <tr>
                <th>Treasure_reward</th>
                <td>{{ card.treasureReward }}</td>
            </tr>
            <tr>
                <th>Lose_description</th>
                <td>{{ card.loseDescription }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_card_index') }}">back to list</a>

    <a href="{{ path('app_card_edit', {'id': card.id}) }}">edit</a>

    {{ include('card/_delete_form.html.twig') }}
{% endblock %}